spring.datasource.url=jdbc:postgresql://localhost:5432/teamo_consulting_db
spring.datasource.username=postgres
spring.datasource.password=Shupe#77

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG